version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/clove/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    stdin_open: true  
    tty: true  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/clove/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: