# Generated by Django 4.1.4 on 2023-02-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'National'), ('C', 'Club')], default='C', max_length=1)),
                ('ext_id', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='util.country')),
            ],
        ),
    ]
