# Generated by Django 4.1.4 on 2023-01-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playable', '0001_initial'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'National'), ('C', 'Club')], default='C', max_length=1)),
                ('ext_id', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='util.country')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='playable.sport')),
            ],
        ),
    ]
