# Generated by Django 4.1.4 on 2023-01-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payable', '0002_initial'),
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsettledbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settledbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payableprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bilateralbet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet', to='playable.bilateralmatch'),
        ),
        migrations.AddField(
            model_name='bilateralbet',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_bets', to='office.office'),
        ),
        migrations.AddField(
            model_name='bilateralbet',
            name='placed_bets',
            field=models.ManyToManyField(related_name='placed_bilateral_bet', to='payable.unsettledbet'),
        ),
        migrations.AddField(
            model_name='bilateralbet',
            name='settled_bets',
            field=models.ManyToManyField(related_name='setelled_bilateral_bet', to='payable.settledbet'),
        ),
    ]
