# Generated by Django 4.1.4 on 2023-01-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payable', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilateralbet',
            name='placed_bets',
        ),
        migrations.RemoveField(
            model_name='bilateralbet',
            name='settled_bets',
        ),
        migrations.AddField(
            model_name='settledbet',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbets', to='payable.bilateralbet'),
        ),
        migrations.AddField(
            model_name='unsettledbet',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubets', to='payable.bilateralbet'),
        ),
    ]
