# Generated by Django 4.1.4 on 2023-02-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playable', '0002_initial'),
        ('office', '0001_initial'),
        ('payable', '0004_remove_bilateralbet_placed_bets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BilateralBet',
            new_name='OfficeBet',
        ),
    ]
