# Generated by Django 4.1.4 on 2023-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ext_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
