# Generated by Django 4.1.4 on 2023-01-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_sport_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playable', '0002_tournament_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilateralMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('match_start_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilateralmatches', to=settings.AUTH_USER_MODEL)),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateam_matches', to='team.team')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bteam_matches', to='team.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='playable.tournament')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='team.team')),
            ],
        ),
    ]
