# Generated by Django 4.1.4 on 2022-12-19 10:36

from django.db import migrations, models
import django.db.models.deletion
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.office'),
        ),
    ]
